Feature/registro movimientos
udistrital/plan_adquisiciones_mid pull request #45
Opened 2021-11-25 09:25 UTC by brayanpasa99

Se realizan cambios para registrar los movimientos asociados a los rubros al agregarlos a un plan de adquisiciones

Tiene que ver con: udistrital/presupuesto_cliente#468

2021-11-27 05:12 UTC, AlexFBP requested changes
- No serializar a mano, cuando se requiera serializar se recomienda:
  1. Tener bien sea una e`struct`ura y crear una instancia, o al menos un `map[string]interface{}`
  2. Serializar la variable creada con `json.Marshal()`
- Aprovechar las funciones [`utils_oas/errorctrl`](https://github.com/udistrital/utils_oas/blob/master/errorctrl/errorctrl.go) para reducir/compactar un poco el código asociado al control de errores. Ver lo comentado en la L27 de `models/movimientos_plan_publicado.go`
- Donde sea que se hagan peticiones a APIs externas, crear un `helpers/<API>/service.go` para guardar las peticiones, con el objetivo de poder reutilizarlas mas adelante. Entre menos código se tenga que escribir, mejor
- Si un helper ya retorna un error estructurado, no es necesario envolverlo, se podría retornar directamente
- Dejar comentados los `logs.Debug()`

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +						return nil, outputError
Revisar: si `ObtenerRegistroMovimientoInversion` retorna el `err`or encapsulado/formateado, esto se puede dejar como:
```suggestion
						return nil, err
```

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +						return nil, outputError
Si `ObtenerMovimientoProcesoExterno` retorna un `err`or formateado, esto se puede dejar como
```suggestion
						return nil, err
```

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +							return nil, outputError
Si `ObtenerMovimientosProcesoExternoPlan` retorna un `err`or formateado, se puede dejar como
```suggestion
							return nil, err
```

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +								return nil, outputError
Si `ObtenerRegistroMovimientoInversion` retorna un `err`or encapsulado, se puede retornar directamente
```suggestion
								return nil, err
```

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +			return nil, outputError
Si `IngresoRenglonPlanFuncionamiento` retorna un `err`or estructurado, se puede retornar directamente
```suggestion
			return nil, err
```

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +				if resultado, errorDatos := resultadoPrueba, errorPrueba; errorDatos != nil {*/
Proceder de manera similar a lo comentado en las L180-188

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +				return nil, outputError
Si `ObtenerMovimientosProcesoExternoPlan` retorna un `err`or formateado
```suggestion
				return nil, err
```

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +						return nil, outputError
Si `ObtenerRegistroMovimientoFuncionamiento` retorna un `err`or estructurado
```suggestion
						return nil, err
```

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +						return nil, outputError
Si `ObtenerMovimientoProcesoExterno` retorna un `err`or estructurado...
```suggestion
						return nil, err
```

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +							return nil, outputError
Si `ObtenerMovimientosProcesoExternoPlan` ...
```suggestion
							return nil, err
```

2021-11-27 05:12 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +								return nil, outputError
Si `ObtenerRegistroMovimientoFuncionamiento` ...
```suggestion
								return nil, err
```

2021-12-04 22:21 UTC, AlexFBP requested changes
En general bien. Los comentarios se podrían resumir en estos tipos:
- Dado que es recurrente, se puede hacer un helper para las serializaciones a JSON (que a su debido tiempo se podría traer mas adelante de `utils_oas/formatdata`
- Si en un `if` siempre se retorna, se puede omitir el `else` para reducir las indentaciones necesarias. Tratar de reducir lo más posible y en donde hayan implicaciones fuertes que no permitan reducir las indentaciones, replicar los comentarios dejados

2021-12-04 22:21 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +			}
Si al final de un `if` se retorna, no se necesita su `else`, el contenido del `else`se puede sacar y dejar despues para eliminar el `else`.

De adentro hacia afuera, se pueden sacar del `else` que engloba a:
- L215-221 colocar después de la L222...
- L197-223 colocar después de la L224...
- L169-225 colocar después de la L226...

... para poder eliminar el `else` y reducir las indentaciones

A modo de ejemplo, ver lo comentado en las L96-102 de `models/plan_adquisicion.go`

2021-12-04 22:21 UTC, AlexFBP commented on models/plan_adquisicion.go
> +			}
Si en el `if` siempre se retorna, se puede omitir el `else`
```suggestion
			}
			idMovimientoObtenido := int(movimientoObtenido.([]interface{})[0].(map[string]interface{})["Id"].(float64))
			if _, err := movimientosCrud.CrearMovimientosPublicacion(idMovimientoObtenido); err != nil {
				logs.Error(err)
				return nil, error
			}
```

2021-12-04 22:21 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +			query := string(data)
Se puede reducir un poquito mas, aprovechando lo comentado a la L30 de `models/movimientos_plan.go`

2021-12-04 22:21 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +			query := string(data)
Se puede reducir un poquito mas, aprovechando lo comentado a la L30 de `models/movimientos_plan.go`

2021-12-04 22:21 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +			return resultadoPlan, nil
Complementando y de manera similar a lo comentado en las L189-224, si en los `if` se está retornando, se puede omitir el `else`, dejando su contenido después. De adentro hacia afuera:
- L280-287 se pueden dejar después de la L288
- L262-289 se pueden dejar después de la L290
- L234-291 se pueden dejar después de la L292
- L228-292 se pueden dejar después de la L293 si se procedió con lo comentado en las L189-224

2021-12-07 00:58 UTC, brayanpasa99 commented on models/movimientos_plan.go
> +package models
Traté de moverlo pero dada la estructura del código aparecían importaciones circulares no soportadas por Go, tratar de solucionarlas implicaba que se tuviera que hacer una refactorización que no hace parte del proceso de dar funcionalidad y que podría plantearse como una optimización futura

2021-12-07 01:43 UTC, brayanpasa99 commented on routers/commentsRouter.go
> +package routers
Hasta donde recuerdo sí

2021-12-07 04:24 UTC, AlexFBP requested changes

2021-12-07 04:24 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +				return nil, outputError
Si `ObtenerRegistroMovimientoInversion` retorna un `err`or formateado, se puede dejar como
```suggestion
				return nil, err
```
_a no ser_ que el `err`or retornado deba procesarse de otra forma

2021-12-07 04:24 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +			return nil, outputError
Si `IngresoRenglonPlanFuncionamiento` retorna un `err`or formateado, se puede dejar así
```suggestion
			return nil, err
```
_a no ser_ que el `err`or retornado deba procesarse de otra forma

2021-12-07 04:26 UTC, AlexFBP commented on conf/app.conf
> +#plan_adquicisiones_crud_url= http://localhost:8080/v1/
Eliminar estas dos líneas, procurando que la última línea de este archivo quede vacía, sin espacios ni nada

2021-12-07 05:19 UTC, brayanpasa99 commented on models/plan_adquisicion.go
>  		error := request.SendJson(beego.AppConfig.String("plan_adquicisiones_crud_url")+"Plan_adquisiciones/"+idStr, "PUT", &PlanAdquisicionPut, PlanAdquisicionActualizar)
No entiendo cómo podría o debería utilizarlo

2021-12-07 05:22 UTC, brayanpasa99 commented on models/registro_plan_adquisicion.go
> +				return nil, outputError
Se procede de otra forma

2021-12-07 05:24 UTC, brayanpasa99 commented on routers/commentsRouter.go
> +package routers
Al eliminar el archivo y correr nuevamente la API, este se vuele a generar. ¿Hay que seguirlo eliminando?

2021-12-09 17:35 UTC, AlexFBP commented
[Solicitud variable en Tuleap Infraestructura](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=44694)

2021-12-09 17:36 UTC, AlexFBP approved these changes

2021-12-09 17:36 UTC, merged