Feature/arreglo movimientos
udistrital/plan_adquisiciones_mid pull request #51
Opened 2022-01-20 06:45 UTC by brayanpasa99

Se realizan ajustes para solucionar las fallas presentadas con la interacción de movimientos CRUD dados los cambios realizados para su paso a producción

Resuelve: udistrital/plan_adquisiciones_cliente#95

2022-01-20 15:04 UTC, AlexFBP requested changes
En general, bien
Algunos comentarios respecto al control de errores y a documentación

2022-01-20 15:04 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +					outputError = errorctrl.Error("IngresoPlanAdquisicion - resultado.(type)", err, "400")
Considerar un [204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) o un [404](https://developer.mozilla.org/es/docs/Web/HTTP/Status/404), en vez del 400

2022-01-20 15:04 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +					outputError = errorctrl.Error("IngresoPlanAdquisicion - resultado.(type)", err, "400")
El 400 estaría bien, este caso sería por culpa del usuario? :thinking:

2022-01-21 00:14 UTC, brayanpasa99 commented on helpers/registrarMovimientoDetalleActualizacionInversion.go
> +		// logs.Debug(reflect.TypeOf(movimientoPreliminarObtenido[0].(map[string]interface{})["FechaCreacion"]))
Se eliminan los comentarios que no son Debug

2022-01-21 00:15 UTC, brayanpasa99 commented on models/registro_plan_adquisicion.go
> +				// logs.Info("resultado: ", resultado.([]interface{}))
Simplificados

2022-01-21 00:18 UTC, brayanpasa99 commented on models/registro_plan_adquisicion.go
> +					outputError = errorctrl.Error("IngresoPlanAdquisicion - resultado.(type)", err, "400")
Lo dejé como 409 - Conflicto

2022-01-21 03:06 UTC, AlexFBP approved these changes

2022-01-21 03:06 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/plan_adquisiciones_mid/105/1/7)

2022-01-25 04:14 UTC, merged