refactor: Manejo de errores y comprobacion datos (Inversion)
udistrital/plan_adquisiciones_mid pull request #54
Opened 2022-03-10 02:56 UTC by brayanpasa99

Resuelve: udistrital/financiera_documentacion#411

2022-03-10 16:01 UTC, diagutierrezro requested changes
Veo todo bien, lo unico es que creo que sería bueno eliminar todos esos comentarios que no sean utiles para cuestiones de documentación o que sean utiles para entender el codigo

2022-03-10 17:50 UTC, DanKazuky requested changes

2022-03-10 17:50 UTC, DanKazuky commented on controllers/plan_adquisicion_por_fuentes.go
> +	// logs.Debug(alertErr.Body)
De mi parte, opino igual sin embargo dejaría la linea 43 comentada ya que si antes estaba, este deberia tener una razón que en un futuro puede ser util, la linea 45 si eliminarla.

2022-03-11 01:04 UTC, brayanpasa99 commented on controllers/plan_adquisicion_por_fuentes.go
> +	// logs.Debug(alertErr.Body)
En general dejé segmentos de código comentados que no eran parte de mi desarrollo y preferí no quitar, de resto, dejé algunos que eran útil para Debug en el futuro

2022-03-25 03:31 UTC, merged