Feature/actualizar planes
udistrital/plan_adquisiciones_mid pull request #55
Opened 2022-03-15 05:16 UTC by brayanpasa99

Retornar el ID del plan publicado para actualizar en configuración

2022-03-16 15:25 UTC, AlexFBP requested changes

2022-03-16 15:25 UTC, AlexFBP commented on models/registro_plan_adquisicion.go
> +	// formatdata.JsonPrint(RegistroPlanAdquisicion)
Simplificar/reducir estos logs

2022-03-16 15:25 UTC, AlexFBP commented on controllers/plan_adquisicion_por_fuentes.go
> +		// c.Ctx.Output.SetStatus(404)
Revisar si esto se puede dejar como estaba, descomentado

2022-03-17 21:45 UTC, brayanpasa99 commented on controllers/plan_adquisicion_por_fuentes.go
> +		// c.Ctx.Output.SetStatus(404)
No se puede

2022-03-17 22:09 UTC, brayanpasa99 commented
Se pone como borrador porque hay ciertas cosas de Arka que no creo deban ir así

![LongitudArka](https://user-images.githubusercontent.com/42362278/158902627-00a011c0-ce91-44e5-83d7-8f2ede9c4161.png)

2022-03-24 22:52 UTC, AlexFBP reviewed
Hasta el momento, bien.

2022-03-25 03:30 UTC, AlexFBP approved these changes

2022-03-25 03:31 UTC, AlexFBP commented
[Build OK](https://hubci.portaloas.udistrital.edu.co/udistrital/plan_adquisiciones_mid/113)

2022-03-25 03:31 UTC, merged